security:
    jwt:
      secret-key: b9fc829dd25923fea6e50d2c283437f00b4974285d186e1ffe920576a7709498 #testing key
      expiration-time: 3600000

spring:
  application:
    name: Billing-System
  h2:
    console:
      enabled: true
      path: /h2-console
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
   # password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #hibernate:
         # ddl-auto: none
    defer-datasource-initialization: true
#server:
#  error:
#    include-binding-errors: always
#    include-message: always